[global]
daemonize = no

[www]
listen = /var/run/php/php8.2-fpm.sock
pm = dynamic
pm.max_children = 5
pm.start_servers = 2
pm.min_spare_servers = 1
pm.max_spare_servers = 3

; Настройка сессий в Redis
session.save_handler = redis
session.save_path = "tcp://redis:6379"
