old_sound_rabbit_mq:
  connections:
    default:
      host: '%env(RABBITMQ_HOST)%'
      port: '%env(RABBITMQ_PORT)%'
      user: '%env(RABBITMQ_DEFAULT_USER)%'
      password: '%env(RABBITMQ_DEFAULT_PASSWORD)%'

  producers:
    email.submitted:
      connection: default
      exchange_options: { name: 'old_sound_rabbit_mq.email.submitted', type: direct }

  consumers:
    email.submitted:
      connection: default
      exchange_options: { name: 'old_sound_rabbit_mq.email.submitted', type: direct }
      queue_options: { name: 'old_sound_rabbit_mq.consumer.email.submitted' }
      callback: App\Queue\Consumer\SendEmailConsumer
