old_sound_rabbit_mq:
    connections:
        default:
            url: '%env(RABBITMQ_URL)%'

    producers:
        chat_update:
            connection: default
            exchange_options: { name: 'old_sound_rabbit_mq.chat_update', type: direct }

        send_message:
            connection: default
            exchange_options: { name: 'old_sound_rabbit_mq.send_message', type: direct }

        edit_message:
            connection: default
            exchange_options: { name: 'old_sound_rabbit_mq.edit_message', type: direct }

    consumers:
        chat_update:
            connection: default
            exchange_options: { name: 'old_sound_rabbit_mq.chat_update', type: direct }
            queue_options: { name: 'old_sound_rabbit_mq.consumer.chat_update' }
            callback: App\Controller\Amqp\ChatUpdate\Consumer
            idle_timeout: 300
            idle_timeout_exit_code: 0
            graceful_max_execution:
                timeout: 1800
                exit_code: 0
            qos_options: { prefetch_size: 0, prefetch_count: 1, global: false }

        send_message:
            connection: default
            exchange_options: { name: 'old_sound_rabbit_mq.send_message', type: direct }
            queue_options: { name: 'old_sound_rabbit_mq.consumer.send_message' }
            callback: App\Controller\Amqp\SendMessage\Consumer
            idle_timeout: 300
            idle_timeout_exit_code: 0
            graceful_max_execution:
                timeout: 1800
                exit_code: 0
            qos_options: { prefetch_size: 0, prefetch_count: 1, global: false }

        edit_message:
            connection: default
            exchange_options: { name: 'old_sound_rabbit_mq.edit_message', type: direct }
            queue_options: { name: 'old_sound_rabbit_mq.consumer.edit_message' }
            callback: App\Controller\Amqp\EditMessage\Consumer
            idle_timeout: 300
            idle_timeout_exit_code: 0
            graceful_max_execution:
                timeout: 1800
                exit_code: 0
            qos_options: { prefetch_size: 0, prefetch_count: 1, global: false }
