COMPOSE_PROJECT_NAME=$1
PUID=$2
PGID=$3
INSTALL_XDEBUG=$4
PHP_UPSTREAM_CONTAINER=$5
PHP_UPSTREAM_PORT=$6
NGINX_HOST_HTTP_PORT=$7
POSTGRES_DB_HOST=$8
POSTGRES_DB_NAME=$9
POSTGRES_PORT=${10}
POSTGRES_USER=${11}
POSTGRES_PASSWORD=${12}
RABBIT_HOST=${13}
RABBIT_PORT=${14}
RABBIT_MANAGEMENT_PORT=${15}
RABBIT_USER=${16}
RABBIT_PASSWORD=${17}

cp .env.dist .env
sed -i "s|COMPOSE_PROJECT_NAME=.*|COMPOSE_PROJECT_NAME=${COMPOSE_PROJECT_NAME}|g" .env
sed -i "s|PUID=.*|PUID=${PUID}|g" .env
sed -i "s|PGID=.*|PGID=${PGID}|g" .env
sed -i "s|INSTALL_XDEBUG=.*|INSTALL_XDEBUG=${INSTALL_XDEBUG}|g" .env
sed -i "s|PHP_UPSTREAM_CONTAINER=.*|PHP_UPSTREAM_CONTAINER=${PHP_UPSTREAM_CONTAINER}|g" .env
sed -i "s|PHP_UPSTREAM_PORT=.*|PHP_UPSTREAM_PORT=${PHP_UPSTREAM_PORT}|g" .env
sed -i "s|NGINX_HOST_HTTP_PORT=.*|NGINX_HOST_HTTP_PORT=${NGINX_HOST_HTTP_PORT}|g" .env
sed -i "s|POSTGRES_DB_HOST=.*|POSTGRES_DB_HOST=${POSTGRES_DB_HOST}|g" .env
sed -i "s|POSTGRES_DB_NAME=.*|POSTGRES_DB_NAME=${POSTGRES_DB_NAME}|g" .env
sed -i "s|POSTGRES_PORT=.*|POSTGRES_PORT=${POSTGRES_PORT}|g" .env
sed -i "s|POSTGRES_USER=.*|POSTGRES_USER=${POSTGRES_USER}|g" .env
sed -i "s|POSTGRES_PASSWORD=.*|POSTGRES_PASSWORD=${POSTGRES_PASSWORD}|g" .env
sed -i "s|RABBIT_HOST=.*|RABBIT_HOST=${RABBIT_HOST}|g" .env
sed -i "s|RABBIT_PORT=.*|RABBIT_PORT=${RABBIT_PORT}|g" .env
sed -i "s|RABBIT_MANAGEMENT_PORT=.*|RABBIT_MANAGEMENT_PORT=${RABBIT_MANAGEMENT_PORT}|g" .env
sed -i "s|RABBIT_USER=.*|RABBIT_USER=${RABBIT_USER}|g" .env
sed -i "s|RABBIT_PASSWORD=.*|RABBIT_PASSWORD=${RABBIT_PASSWORD}|g" .env
