# Список шагов
stages:
  - build # Подготовка проекта
  - test # Прогон автотестов
  - deploy # Деплой кода на прод
  - rollback # Откат изменений

build-job:
  stage: build
  script:
    - echo "Building the application..."
    - ls -l
    # Команды для сборки проекта
  tags:
    - makhov-runner

deploy-job:
  stage: deploy
  only:
    - main # Этот job выполняется только на основной ветке
  script:
    - echo "Deploying to VPS..."
    - cd /var/www/cicd-makhov-2025  # Переходим в директорию проекта
    - git pull  # Обновляем код
    - ./deploy.sh  # Запускаем скрипт деплоя
    - ./reload.sh  # Перечитываем конфиги сервисов
  tags:
    - makhov-runner

test-job:
  stage: test
  script:
    - echo "Running tests 1..."
    # команды для запуска тестов
  tags:
    - makhov-runner

rollback-job:
  stage: rollback
  only:
    - main
  script:
    - echo "Rolling back on VPS..."
    - cd /var/www/cicd-makhov-2025  # Переходим в директорию проекта
    - ./rollback.sh  # Запускаем скрипт отката
    - ./reload.sh  # Перечитываем конфиги сервисов
  when: manual  # Запуск в ручном режиме
  tags:
    - makhov-runner

