-- This script was generated by the ERD tool in pgAdmin 4.
-- Please log an issue at https://github.com/pgadmin-org/pgadmin4/issues/new/choose if you find any bugs, including reproduction steps.
BEGIN;


CREATE TABLE IF NOT EXISTS public."Cinema_halls"
(
    id bigint NOT NULL,
    name character varying(45) COLLATE pg_catalog."default",
    effects bigint NOT NULL,
    seats_count bigint,
    CONSTRAINT "Cinema_halls_pkey" PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public."Cinema_sessions"
(
    id bigint NOT NULL GENERATED ALWAYS AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 ),
    session_start_at timestamp without time zone,
    session_end_at timestamp without time zone,
    film_id bigint NOT NULL,
    cinema_hall_id bigint NOT NULL,
    CONSTRAINT id PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public."Directors"
(
    id bigint NOT NULL,
    first_name character varying(45) COLLATE pg_catalog."default",
    last_name character varying(45) COLLATE pg_catalog."default",
    CONSTRAINT "Directors_pkey" PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public."Effects"
(
    id bigint NOT NULL,
    name character varying(45) COLLATE pg_catalog."default" NOT NULL,
    CONSTRAINT "Effects_pkey" PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public."Films"
(
    id bigint NOT NULL,
    name character varying(255) COLLATE pg_catalog."default" NOT NULL,
    duration character varying(45) COLLATE pg_catalog."default",
    manufacturer bigint,
    director bigint,
    description character varying(255) COLLATE pg_catalog."default",
    rental_company bigint NOT NULL,
    age_limits bigint NOT NULL,
    actors text COLLATE pg_catalog."default",
    film_links text COLLATE pg_catalog."default",
    CONSTRAINT "Films_pkey" PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public."Films_Genres"
(
    id bigint NOT NULL,
    film_id bigint,
    genre_id bigint,
    CONSTRAINT "Films_Genres_pkey" PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public."Films_attribute"
(
    id bigint NOT NULL,
    film_id bigint,
    name character varying(200) COLLATE pg_catalog."default",
    code character varying(200) COLLATE pg_catalog."default",
    CONSTRAINT "Films_attribute_pkey" PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public."Films_attributeType"
(
    id bigint NOT NULL,
    type character varying(100) COLLATE pg_catalog."default",
    attribute_id bigint,
    CONSTRAINT "Films_attributeType_pkey" PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public."Films_attributeValue"
(
    id bigint NOT NULL,
    value_text text COLLATE pg_catalog."default",
    value_boolean boolean,
    value_datetime timestamp without time zone,
    attributetype_id bigint,
    value_int bigint,
    value_float double precision,
    CONSTRAINT "Films_arrtibuteValue_pkey" PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public."Genres"
(
    id bigint NOT NULL,
    name character varying(100) COLLATE pg_catalog."default",
    CONSTRAINT "Genres_pkey" PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public."Manufacturers"
(
    id bigint NOT NULL,
    country character varying(255) COLLATE pg_catalog."default" NOT NULL,
    CONSTRAINT "Manufacturers_pkey" PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public."Prices"
(
    id bigint NOT NULL,
    film_id bigint NOT NULL,
    base_price money,
    night_price money,
    day_price money,
    surcharge_series money,
    CONSTRAINT "Prices_pkey" PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public."Rental_companies"
(
    id bigint NOT NULL,
    name character varying(100) COLLATE pg_catalog."default" NOT NULL,
    phone character varying(45) COLLATE pg_catalog."default" NOT NULL,
    email character varying(45) COLLATE pg_catalog."default",
    CONSTRAINT "Rental_companies_pkey" PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public."Scheme_halls"
(
    id bigint NOT NULL,
    hall_id bigint,
    series bigint NOT NULL,
    seat bigint NOT NULL,
    status boolean DEFAULT false,
    CONSTRAINT "Scheme_halls_pkey" PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public."Tikets"
(
    id bigint NOT NULL GENERATED ALWAYS AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 ),
    session_id bigint NOT NULL,
    price money,
    series bigint,
    seat bigint,
    CONSTRAINT "Tikets_pkey" PRIMARY KEY (id)
);

ALTER TABLE IF EXISTS public."Cinema_halls"
    ADD CONSTRAINT "fk_Cinema_halls_1" FOREIGN KEY (effects)
        REFERENCES public."Effects" (id) MATCH SIMPLE
        ON UPDATE CASCADE
        ON DELETE CASCADE
        NOT VALID;
CREATE INDEX IF NOT EXISTS "fki_fk_Cinema_halls_1"
    ON public."Cinema_halls"(effects);


ALTER TABLE IF EXISTS public."Cinema_sessions"
    ADD CONSTRAINT "fk_Cinema_session_1" FOREIGN KEY (film_id)
        REFERENCES public."Films" (id) MATCH SIMPLE
        ON UPDATE CASCADE
        ON DELETE CASCADE
        NOT VALID;
CREATE INDEX IF NOT EXISTS "fki_fk_Cinema_session_1"
    ON public."Cinema_sessions"(film_id);


ALTER TABLE IF EXISTS public."Films"
    ADD CONSTRAINT fk_films_1 FOREIGN KEY (rental_company)
        REFERENCES public."Rental_companies" (id) MATCH SIMPLE
        ON UPDATE CASCADE
        ON DELETE CASCADE
        NOT VALID;
CREATE INDEX IF NOT EXISTS fki_fk_films_1
    ON public."Films"(rental_company);


ALTER TABLE IF EXISTS public."Films"
    ADD CONSTRAINT fk_films_2 FOREIGN KEY (manufacturer)
        REFERENCES public."Manufacturers" (id) MATCH SIMPLE
        ON UPDATE CASCADE
        ON DELETE CASCADE
        NOT VALID;
CREATE INDEX IF NOT EXISTS fki_fk_films_2
    ON public."Films"(manufacturer);


ALTER TABLE IF EXISTS public."Films"
    ADD CONSTRAINT fk_films_3 FOREIGN KEY (director)
        REFERENCES public."Directors" (id) MATCH SIMPLE
        ON UPDATE CASCADE
        ON DELETE CASCADE
        NOT VALID;
CREATE INDEX IF NOT EXISTS fki_fk_films_3
    ON public."Films"(director);


ALTER TABLE IF EXISTS public."Films_Genres"
    ADD CONSTRAINT "fk_Films_Genres_1" FOREIGN KEY (genre_id)
        REFERENCES public."Genres" (id) MATCH SIMPLE
        ON UPDATE CASCADE
        ON DELETE CASCADE
        NOT VALID;
CREATE INDEX IF NOT EXISTS "fki_fk_Films_Genres_1"
    ON public."Films_Genres"(genre_id);


ALTER TABLE IF EXISTS public."Films_Genres"
    ADD CONSTRAINT "fk_Films_Genres_2" FOREIGN KEY (film_id)
        REFERENCES public."Films" (id) MATCH SIMPLE
        ON UPDATE CASCADE
        ON DELETE CASCADE
        NOT VALID;
CREATE INDEX IF NOT EXISTS "fki_fk_Films_Genres_2"
    ON public."Films_Genres"(film_id);


ALTER TABLE IF EXISTS public."Films_attribute"
    ADD CONSTRAINT "fk_Films_attribute_1" FOREIGN KEY (film_id)
        REFERENCES public."Films" (id) MATCH SIMPLE
        ON UPDATE CASCADE
        ON DELETE CASCADE;
CREATE INDEX IF NOT EXISTS "fki_fk_Films_attribute_1"
    ON public."Films_attribute"(film_id);


ALTER TABLE IF EXISTS public."Films_attributeType"
    ADD CONSTRAINT "fk_Films_attributeType_1" FOREIGN KEY (attribute_id)
        REFERENCES public."Films_attribute" (id) MATCH SIMPLE
        ON UPDATE CASCADE
        ON DELETE CASCADE
        NOT VALID;
CREATE INDEX IF NOT EXISTS "fki_fk_Films_attributeType_1"
    ON public."Films_attributeType"(attribute_id);


ALTER TABLE IF EXISTS public."Films_attributeValue"
    ADD CONSTRAINT "fk_Films_attributeValue_1" FOREIGN KEY (attributetype_id)
        REFERENCES public."Films_attributeType" (id) MATCH SIMPLE
        ON UPDATE CASCADE
        ON DELETE CASCADE;
CREATE INDEX IF NOT EXISTS "fki_fk_Films_attributeValue_1"
    ON public."Films_attributeValue"(attributetype_id);


ALTER TABLE IF EXISTS public."Prices"
    ADD CONSTRAINT fk_prices_1 FOREIGN KEY (film_id)
        REFERENCES public."Films" (id) MATCH SIMPLE
        ON UPDATE CASCADE
        ON DELETE CASCADE
        NOT VALID;
CREATE INDEX IF NOT EXISTS fki_fk_prices_1
    ON public."Prices"(film_id);


ALTER TABLE IF EXISTS public."Scheme_halls"
    ADD CONSTRAINT "fk_Scheme_halls_1" FOREIGN KEY (hall_id)
        REFERENCES public."Cinema_halls" (id) MATCH SIMPLE
        ON UPDATE CASCADE
        ON DELETE CASCADE
        NOT VALID;
CREATE INDEX IF NOT EXISTS "fki_fk_Scheme_halls_1"
    ON public."Scheme_halls"(hall_id);


ALTER TABLE IF EXISTS public."Tikets"
    ADD CONSTRAINT "fk_Tikets_1" FOREIGN KEY (session_id)
        REFERENCES public."Cinema_sessions" (id) MATCH SIMPLE
        ON UPDATE CASCADE
        ON DELETE CASCADE
        NOT VALID;
CREATE INDEX IF NOT EXISTS "fki_fk_Tikets_1"
    ON public."Tikets"(session_id);

END;