MYSQL_DATABASE=$1
MYSQL_USER=$2
MYSQL_PASSWORD=$3
MYSQL_CONTAINER_NAME=$4
MYSQL_ROOT_PASSWORD=$5
SERVER_NAME=$6

cp .env.example .env
sed -i "s|MYSQL_DATABASE=.*|MYSQL_DATABASE=${MYSQL_DATABASE}|g" .env
sed -i "s|MYSQL_USER=.*|MYSQL_USER=${MYSQL_USER}|g" .env
sed -i "s|MYSQL_PASSWORD=.*|MYSQL_PASSWORD=${MYSQL_PASSWORD}|g" .env
sed -i "s|MYSQL_CONTAINER_NAME=.*|MYSQL_CONTAINER_NAME=${MYSQL_CONTAINER_NAME}|g" .env
sed -i "s|MYSQL_ROOT_PASSWORD=.*|MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}|g" .env
sed -i "s|%SERVER_NAME%|${SERVER_NAME}|g" docker/nginx/nginx.conf
