-- INSERT INTO films VALUES ('master_i_margarita', 'Мастер и Маргарита', 500.00, 700.00);
-- INSERT INTO films VALUES ('onegin', 'Онегин', 400.00, 600.00);
-- INSERT INTO films VALUES ('duna_2', 'Дюна 2', 450.00, 600.00);
--
-- INSERT INTO sessions VALUES ('master_13', 'master_i_margarita', '13:00:00');
-- INSERT INTO sessions VALUES ('master_17', 'master_i_margarita', '17:00:00');
-- INSERT INTO sessions VALUES ('onegin_11', 'onegin', '11:00:00');
-- INSERT INTO sessions VALUES ('onegin_16', 'onegin', '16:00:00');
-- INSERT INTO sessions VALUES ('duna2_13', 'duna_2', '13:00:00');
-- INSERT INTO sessions VALUES ('duna2_20', 'duna_2', '20:00:00');


INSERT INTO seats (id, seat, luxe, row, hall, booked) VALUES (DEFAULT, 1, false, 0, 1, false);
INSERT INTO seats (id, seat, luxe, row, hall, booked) VALUES (DEFAULT, 2, false, 0, 1, false);
INSERT INTO seats (id, seat, luxe, row, hall, booked) VALUES (DEFAULT, 3, false, 0, 1, false);
INSERT INTO seats (id, seat, luxe, row, hall, booked) VALUES (DEFAULT, 4, false, 0, 1, false);
INSERT INTO seats (id, seat, luxe, row, hall, booked) VALUES (DEFAULT, 5, false, 0, 1, false);
INSERT INTO seats (id, seat, luxe, row, hall, booked) VALUES (DEFAULT, 6, false, 0, 1, false);
INSERT INTO seats (id, seat, luxe, row, hall, booked) VALUES (DEFAULT, 7, false, 0, 1, false);
INSERT INTO seats (id, seat, luxe, row, hall, booked) VALUES (DEFAULT, 8, false, 0, 1, false);
INSERT INTO seats (id, seat, luxe, row, hall, booked) VALUES (DEFAULT, 9, false, 0, 1, false);
INSERT INTO seats (id, seat, luxe, row, hall, booked) VALUES (DEFAULT, 10, false, 0, 1, false);
INSERT INTO seats (id, seat, luxe, row, hall, booked) VALUES (DEFAULT, 11, false, 0, 1, false);
INSERT INTO seats (id, seat, luxe, row, hall, booked) VALUES (DEFAULT, 12, false, 0, 1, false);
INSERT INTO seats (id, seat, luxe, row, hall, booked) VALUES (DEFAULT, 13, false, 0, 1, false);
INSERT INTO seats (id, seat, luxe, row, hall, booked) VALUES (DEFAULT, 14, false, 0, 1, false);
INSERT INTO seats (id, seat, luxe, row, hall, booked) VALUES (DEFAULT, 15, false, 0, 1, false);
INSERT INTO seats (id, seat, luxe, row, hall, booked) VALUES (DEFAULT, 16, false, 0, 1, false);
INSERT INTO seats (id, seat, luxe, row, hall, booked) VALUES (DEFAULT, 17, false, 0, 1, false);
INSERT INTO seats (id, seat, luxe, row, hall, booked) VALUES (DEFAULT, 18, false, 0, 1, false);
INSERT INTO seats (id, seat, luxe, row, hall, booked) VALUES (DEFAULT, 19, false, 0, 1, false);

INSERT INTO seats (id, seat, luxe, row, hall, booked) VALUES (DEFAULT, 1, false, 1, 1, false);
INSERT INTO seats (id, seat, luxe, row, hall, booked) VALUES (DEFAULT, 2, false, 1, 1, false);
INSERT INTO seats (id, seat, luxe, row, hall, booked) VALUES (DEFAULT, 3, false, 1, 1, false);
INSERT INTO seats (id, seat, luxe, row, hall, booked) VALUES (DEFAULT, 4, false, 1, 1, false);
INSERT INTO seats (id, seat, luxe, row, hall, booked) VALUES (DEFAULT, 5, false, 1, 1, false);
INSERT INTO seats (id, seat, luxe, row, hall, booked) VALUES (DEFAULT, 6, false, 1, 1, false);
INSERT INTO seats (id, seat, luxe, row, hall, booked) VALUES (DEFAULT, 7, false, 1, 1, false);
INSERT INTO seats (id, seat, luxe, row, hall, booked) VALUES (DEFAULT, 8, false, 1, 1, false);
INSERT INTO seats (id, seat, luxe, row, hall, booked) VALUES (DEFAULT, 9, false, 1, 1, false);
INSERT INTO seats (id, seat, luxe, row, hall, booked) VALUES (DEFAULT, 10, false, 1, 1, false);
INSERT INTO seats (id, seat, luxe, row, hall, booked) VALUES (DEFAULT, 11, false, 1, 1, false);
INSERT INTO seats (id, seat, luxe, row, hall, booked) VALUES (DEFAULT, 12, false, 1, 1, false);
INSERT INTO seats (id, seat, luxe, row, hall, booked) VALUES (DEFAULT, 13, false, 1, 1, false);
INSERT INTO seats (id, seat, luxe, row, hall, booked) VALUES (DEFAULT, 14, false, 1, 1, false);
INSERT INTO seats (id, seat, luxe, row, hall, booked) VALUES (DEFAULT, 15, false, 1, 1, false);
INSERT INTO seats (id, seat, luxe, row, hall, booked) VALUES (DEFAULT, 16, false, 1, 1, false);
INSERT INTO seats (id, seat, luxe, row, hall, booked) VALUES (DEFAULT, 17, false, 1, 1, false);
INSERT INTO seats (id, seat, luxe, row, hall, booked) VALUES (DEFAULT, 18, false, 1, 1, false);
INSERT INTO seats (id, seat, luxe, row, hall, booked) VALUES (DEFAULT, 19, false, 1, 1, false);
INSERT INTO seats (id, seat, luxe, row, hall, booked) VALUES (DEFAULT, 20, false, 1, 1, false);
INSERT INTO seats (id, seat, luxe, row, hall, booked) VALUES (DEFAULT, 21, false, 1, 1, false);

INSERT INTO seats (id, seat, luxe, row, hall, booked) VALUES (DEFAULT, 1, false, 2, 1, false);
INSERT INTO seats (id, seat, luxe, row, hall, booked) VALUES (DEFAULT, 2, false, 2, 1, false);
INSERT INTO seats (id, seat, luxe, row, hall, booked) VALUES (DEFAULT, 3, false, 2, 1, false);
INSERT INTO seats (id, seat, luxe, row, hall, booked) VALUES (DEFAULT, 4, false, 2, 1, false);
INSERT INTO seats (id, seat, luxe, row, hall, booked) VALUES (DEFAULT, 5, false, 2, 1, false);
INSERT INTO seats (id, seat, luxe, row, hall, booked) VALUES (DEFAULT, 6, false, 2, 1, false);
INSERT INTO seats (id, seat, luxe, row, hall, booked) VALUES (DEFAULT, 7, false, 2, 1, false);
INSERT INTO seats (id, seat, luxe, row, hall, booked) VALUES (DEFAULT, 8, false, 2, 1, false);
INSERT INTO seats (id, seat, luxe, row, hall, booked) VALUES (DEFAULT, 9, false, 2, 1, false);
INSERT INTO seats (id, seat, luxe, row, hall, booked) VALUES (DEFAULT, 10, false, 2, 1, false);
INSERT INTO seats (id, seat, luxe, row, hall, booked) VALUES (DEFAULT, 11, false, 2, 1, false);
INSERT INTO seats (id, seat, luxe, row, hall, booked) VALUES (DEFAULT, 12, false, 2, 1, false);
INSERT INTO seats (id, seat, luxe, row, hall, booked) VALUES (DEFAULT, 13, false, 2, 1, false);
INSERT INTO seats (id, seat, luxe, row, hall, booked) VALUES (DEFAULT, 14, false, 2, 1, false);
INSERT INTO seats (id, seat, luxe, row, hall, booked) VALUES (DEFAULT, 15, false, 2, 1, false);
INSERT INTO seats (id, seat, luxe, row, hall, booked) VALUES (DEFAULT, 16, false, 2, 1, false);
INSERT INTO seats (id, seat, luxe, row, hall, booked) VALUES (DEFAULT, 17, false, 2, 1, false);
INSERT INTO seats (id, seat, luxe, row, hall, booked) VALUES (DEFAULT, 18, false, 2, 1, false);
INSERT INTO seats (id, seat, luxe, row, hall, booked) VALUES (DEFAULT, 19, false, 2, 1, false);
INSERT INTO seats (id, seat, luxe, row, hall, booked) VALUES (DEFAULT, 20, false, 2, 1, false);
INSERT INTO seats (id, seat, luxe, row, hall, booked) VALUES (DEFAULT, 21, false, 2, 1, false);
INSERT INTO seats (id, seat, luxe, row, hall, booked) VALUES (DEFAULT, 22, false, 2, 1, false);
INSERT INTO seats (id, seat, luxe, row, hall, booked) VALUES (DEFAULT, 23, false, 2, 1, false);

INSERT INTO seats (id, seat, luxe, row, hall, booked) VALUES (DEFAULT, 1, false, 3, 1, false);
INSERT INTO seats (id, seat, luxe, row, hall, booked) VALUES (DEFAULT, 2, false, 3, 1, false);
INSERT INTO seats (id, seat, luxe, row, hall, booked) VALUES (DEFAULT, 3, false, 3, 1, false);
INSERT INTO seats (id, seat, luxe, row, hall, booked) VALUES (DEFAULT, 4, false, 3, 1, false);
INSERT INTO seats (id, seat, luxe, row, hall, booked) VALUES (DEFAULT, 5, false, 3, 1, false);
INSERT INTO seats (id, seat, luxe, row, hall, booked) VALUES (DEFAULT, 6, true, 3, 1, false);
INSERT INTO seats (id, seat, luxe, row, hall, booked) VALUES (DEFAULT, 7, true, 3, 1, false);
INSERT INTO seats (id, seat, luxe, row, hall, booked) VALUES (DEFAULT, 8, true, 3, 1, false);
INSERT INTO seats (id, seat, luxe, row, hall, booked) VALUES (DEFAULT, 9, true, 3, 1, false);
INSERT INTO seats (id, seat, luxe, row, hall, booked) VALUES (DEFAULT, 10, true, 3, 1, false);
INSERT INTO seats (id, seat, luxe, row, hall, booked) VALUES (DEFAULT, 11, true, 3, 1, false);
INSERT INTO seats (id, seat, luxe, row, hall, booked) VALUES (DEFAULT, 12, true, 3, 1, false);
INSERT INTO seats (id, seat, luxe, row, hall, booked) VALUES (DEFAULT, 13, true, 3, 1, false);
INSERT INTO seats (id, seat, luxe, row, hall, booked) VALUES (DEFAULT, 14, true, 3, 1, false);
INSERT INTO seats (id, seat, luxe, row, hall, booked) VALUES (DEFAULT, 15, true, 3, 1, false);
INSERT INTO seats (id, seat, luxe, row, hall, booked) VALUES (DEFAULT, 16, true, 3, 1, false);
INSERT INTO seats (id, seat, luxe, row, hall, booked) VALUES (DEFAULT, 17, true, 3, 1, false);
INSERT INTO seats (id, seat, luxe, row, hall, booked) VALUES (DEFAULT, 18, true, 3, 1, false);
INSERT INTO seats (id, seat, luxe, row, hall, booked) VALUES (DEFAULT, 19, true, 3, 1, false);
INSERT INTO seats (id, seat, luxe, row, hall, booked) VALUES (DEFAULT, 20, true, 3, 1, false);
INSERT INTO seats (id, seat, luxe, row, hall, booked) VALUES (DEFAULT, 21, false, 3, 1, false);
INSERT INTO seats (id, seat, luxe, row, hall, booked) VALUES (DEFAULT, 22, false, 3, 1, false);
INSERT INTO seats (id, seat, luxe, row, hall, booked) VALUES (DEFAULT, 23, false, 3, 1, false);
INSERT INTO seats (id, seat, luxe, row, hall, booked) VALUES (DEFAULT, 24, false, 3, 1, false);

INSERT INTO seats (id, seat, luxe, row, hall, booked) VALUES (DEFAULT, 1, false, 4, 1, false);
INSERT INTO seats (id, seat, luxe, row, hall, booked) VALUES (DEFAULT, 2, false, 4, 1, false);
INSERT INTO seats (id, seat, luxe, row, hall, booked) VALUES (DEFAULT, 3, false, 4, 1, false);
INSERT INTO seats (id, seat, luxe, row, hall, booked) VALUES (DEFAULT, 4, false, 4, 1, false);
INSERT INTO seats (id, seat, luxe, row, hall, booked) VALUES (DEFAULT, 5, false, 4, 1, false);
INSERT INTO seats (id, seat, luxe, row, hall, booked) VALUES (DEFAULT, 6, true, 4, 1, false);
INSERT INTO seats (id, seat, luxe, row, hall, booked) VALUES (DEFAULT, 7, true, 4, 1, false);
INSERT INTO seats (id, seat, luxe, row, hall, booked) VALUES (DEFAULT, 8, true, 4, 1, false);
INSERT INTO seats (id, seat, luxe, row, hall, booked) VALUES (DEFAULT, 9, true, 4, 1, false);
INSERT INTO seats (id, seat, luxe, row, hall, booked) VALUES (DEFAULT, 10, true, 4, 1, false);
INSERT INTO seats (id, seat, luxe, row, hall, booked) VALUES (DEFAULT, 11, true, 4, 1, false);
INSERT INTO seats (id, seat, luxe, row, hall, booked) VALUES (DEFAULT, 12, true, 4, 1, false);
INSERT INTO seats (id, seat, luxe, row, hall, booked) VALUES (DEFAULT, 13, true, 4, 1, false);
INSERT INTO seats (id, seat, luxe, row, hall, booked) VALUES (DEFAULT, 14, true, 4, 1, false);
INSERT INTO seats (id, seat, luxe, row, hall, booked) VALUES (DEFAULT, 15, true, 4, 1, false);
INSERT INTO seats (id, seat, luxe, row, hall, booked) VALUES (DEFAULT, 16, true, 4, 1, false);
INSERT INTO seats (id, seat, luxe, row, hall, booked) VALUES (DEFAULT, 17, true, 4, 1, false);
INSERT INTO seats (id, seat, luxe, row, hall, booked) VALUES (DEFAULT, 18, true, 4, 1, false);
INSERT INTO seats (id, seat, luxe, row, hall, booked) VALUES (DEFAULT, 19, true, 4, 1, false);
INSERT INTO seats (id, seat, luxe, row, hall, booked) VALUES (DEFAULT, 20, true, 4, 1, false);
INSERT INTO seats (id, seat, luxe, row, hall, booked) VALUES (DEFAULT, 21, true, 4, 1, false);
INSERT INTO seats (id, seat, luxe, row, hall, booked) VALUES (DEFAULT, 22, true, 4, 1, false);
INSERT INTO seats (id, seat, luxe, row, hall, booked) VALUES (DEFAULT, 23, false, 4, 1, false);
INSERT INTO seats (id, seat, luxe, row, hall, booked) VALUES (DEFAULT, 24, false, 4, 1, false);
INSERT INTO seats (id, seat, luxe, row, hall, booked) VALUES (DEFAULT, 25, false, 4, 1, false);
INSERT INTO seats (id, seat, luxe, row, hall, booked) VALUES (DEFAULT, 26, false, 4, 1, false);

INSERT INTO seats (id, seat, luxe, row, hall, booked) VALUES (DEFAULT, 1, false, 5, 1, false);
INSERT INTO seats (id, seat, luxe, row, hall, booked) VALUES (DEFAULT, 2, false, 5, 1, false);
INSERT INTO seats (id, seat, luxe, row, hall, booked) VALUES (DEFAULT, 3, false, 5, 1, false);
INSERT INTO seats (id, seat, luxe, row, hall, booked) VALUES (DEFAULT, 4, false, 5, 1, false);
INSERT INTO seats (id, seat, luxe, row, hall, booked) VALUES (DEFAULT, 5, false, 5, 1, false);
INSERT INTO seats (id, seat, luxe, row, hall, booked) VALUES (DEFAULT, 6, true, 5, 1, false);
INSERT INTO seats (id, seat, luxe, row, hall, booked) VALUES (DEFAULT, 7, true, 5, 1, false);
INSERT INTO seats (id, seat, luxe, row, hall, booked) VALUES (DEFAULT, 8, true, 5, 1, false);
INSERT INTO seats (id, seat, luxe, row, hall, booked) VALUES (DEFAULT, 9, true, 5, 1, false);
INSERT INTO seats (id, seat, luxe, row, hall, booked) VALUES (DEFAULT, 10, true, 5, 1, false);
INSERT INTO seats (id, seat, luxe, row, hall, booked) VALUES (DEFAULT, 11, true, 5, 1, false);
INSERT INTO seats (id, seat, luxe, row, hall, booked) VALUES (DEFAULT, 12, true, 5, 1, false);
INSERT INTO seats (id, seat, luxe, row, hall, booked) VALUES (DEFAULT, 13, true, 5, 1, false);
INSERT INTO seats (id, seat, luxe, row, hall, booked) VALUES (DEFAULT, 14, true, 5, 1, false);
INSERT INTO seats (id, seat, luxe, row, hall, booked) VALUES (DEFAULT, 15, true, 5, 1, false);
INSERT INTO seats (id, seat, luxe, row, hall, booked) VALUES (DEFAULT, 16, true, 5, 1, false);
INSERT INTO seats (id, seat, luxe, row, hall, booked) VALUES (DEFAULT, 17, true, 5, 1, false);
INSERT INTO seats (id, seat, luxe, row, hall, booked) VALUES (DEFAULT, 18, true, 5, 1, false);
INSERT INTO seats (id, seat, luxe, row, hall, booked) VALUES (DEFAULT, 19, true, 5, 1, false);
INSERT INTO seats (id, seat, luxe, row, hall, booked) VALUES (DEFAULT, 20, true, 5, 1, false);
INSERT INTO seats (id, seat, luxe, row, hall, booked) VALUES (DEFAULT, 21, true, 5, 1, false);
INSERT INTO seats (id, seat, luxe, row, hall, booked) VALUES (DEFAULT, 22, true, 5, 1, false);
INSERT INTO seats (id, seat, luxe, row, hall, booked) VALUES (DEFAULT, 23, false, 5, 1, false);
INSERT INTO seats (id, seat, luxe, row, hall, booked) VALUES (DEFAULT, 24, false, 5, 1, false);
INSERT INTO seats (id, seat, luxe, row, hall, booked) VALUES (DEFAULT, 25, false, 5, 1, false);
INSERT INTO seats (id, seat, luxe, row, hall, booked) VALUES (DEFAULT, 26, false, 5, 1, false);
INSERT INTO seats (id, seat, luxe, row, hall, booked) VALUES (DEFAULT, 27, false, 5, 1, false);
INSERT INTO seats (id, seat, luxe, row, hall, booked) VALUES (DEFAULT, 28, false, 5, 1, false);