services:
  nginx:
    container_name: MyNginx
    ports:
      - "80:80"
    build:
      context: ./context/nginx
      dockerfile: dockerfile
    networks:
      - devweb
    volumes:
      - ./project/htdocs/public_html:/var/www/html/public_html
      - ./logs/nginx:/var/log/nginx/
    depends_on:
      - php

  php:
    container_name: MyPhp
    build:
      context: ./context/php
      dockerfile: dockerfile
    volumes:
     - ./project/htdocs/:/var/www/html/
     - ./logs/php.log:/var/log/fpm-php.www.log
    networks:
      - devweb


  composer:
    build:
      context: ./context/composer
      dockerfile: Dockerfile
    container_name: MyComposer
    working_dir: /var/www/html
    volumes:
      - ./project/htdocs/:/var/www/
    command: ["composer", "dump-autoload"]
    networks:
      - devweb
    depends_on:
      - php



networks:
  devweb:
    name: devweb
    driver: bridge