-- MySQL Script generated by MySQL Workbench
-- Ср 06 мар 2024 21:33:36
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET cp1251 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`Rental_companies`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Rental_companies` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(100) NOT NULL,
  `phone` VARCHAR(45) NOT NULL,
  `email` VARCHAR(45) NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `company_id_UNIQUE` (`id` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Manufacturers`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Manufacturers` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `country` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Genres`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Genres` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(100) NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Directors`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Directors` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `first_name` VARCHAR(45) NOT NULL,
  `last_name` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Films`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Films` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  `duration` VARCHAR(45) NULL,
  `genre` INT NOT NULL,
  `manufacturer` INT NOT NULL,
  `director` INT NOT NULL,
  `description` VARCHAR(255) NULL,
  `rental_company` INT NOT NULL,
  `age_limits` INT NOT NULL,
  `actors` TEXT(4096) NULL,
  `film_links` TEXT(4096) NULL,
  `start_rental_at` DATETIME NULL,
  `end_rental_at` DATETIME NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_Films_1_idx` (`rental_company` ASC) VISIBLE,
  INDEX `fk_Films_2_idx` (`manufacturer` ASC) VISIBLE,
  INDEX `fk_Films_3_idx` (`genre` ASC) VISIBLE,
  INDEX `fk_Films_4_idx` (`director` ASC) VISIBLE,
  CONSTRAINT `fk_Films_1`
    FOREIGN KEY (`rental_company`)
    REFERENCES `mydb`.`Rental_companies` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_Films_2`
    FOREIGN KEY (`manufacturer`)
    REFERENCES `mydb`.`Manufacturers` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_Films_3`
    FOREIGN KEY (`genre`)
    REFERENCES `mydb`.`Genres` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_Films_4`
    FOREIGN KEY (`director`)
    REFERENCES `mydb`.`Directors` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Effects`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Effects` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Cinema_halls`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Cinema_halls` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  `effects` INT NOT NULL,
  `seats_count` INT NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `hall_id_UNIQUE` (`id` ASC) VISIBLE,
  INDEX `fk_Cinema_halls_1_idx` (`effects` ASC) VISIBLE,
  CONSTRAINT `fk_Cinema_halls_1`
    FOREIGN KEY (`effects`)
    REFERENCES `mydb`.`Effects` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Scheme_halls`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Scheme_halls` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `hall_id` INT NOT NULL,
  `series` INT NOT NULL,
  `seat` INT NOT NULL,
  `status` TINYINT NOT NULL DEFAULT 0,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `scheme_id_UNIQUE` (`id` ASC) VISIBLE,
  INDEX `hall_id_index` USING BTREE (`hall_id`) VISIBLE,
  CONSTRAINT `fk_Scheme_halls_1`
    FOREIGN KEY (`hall_id`)
    REFERENCES `mydb`.`Cinema_halls` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Cinema_sessions`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Cinema_sessions` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `session_start_at` DATETIME NULL,
  `session_end_at` DATETIME NULL,
  `film_id` INT NOT NULL,
  `cinema_hall_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `session_id_UNIQUE` (`id` ASC) VISIBLE,
  INDEX `hall_id_index` USING BTREE (`cinema_hall_id`) VISIBLE,
  INDEX `film_id_index` (`film_id` ASC) VISIBLE,
  CONSTRAINT `fk_Cinema_sessions_1`
    FOREIGN KEY (`film_id`)
    REFERENCES `mydb`.`Films` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_Cinema_sessions_2`
    FOREIGN KEY (`cinema_hall_id`)
    REFERENCES `mydb`.`Cinema_halls` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Prices`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Prices` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `film_id` INT NOT NULL,
  `base_price` DECIMAL(6,2) NOT NULL,
  `night_price` DECIMAL(6,2) NULL,
  `day_price` DECIMAL(6,2) NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `price_id_UNIQUE` (`id` ASC) VISIBLE,
  INDEX `fk_Prices_1_idx` (`film_id` ASC) VISIBLE,
  CONSTRAINT `fk_Prices_1`
    FOREIGN KEY (`film_id`)
    REFERENCES `mydb`.`Films` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Tikets`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Tikets` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `session_id` INT NOT NULL,
  `price` DECIMAL(6,2) NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `tiket_id_UNIQUE` (`id` ASC) VISIBLE,
  INDEX `fk_Tikets_1_idx` (`session_id` ASC) VISIBLE,
  CONSTRAINT `fk_Tikets_1`
    FOREIGN KEY (`session_id`)
    REFERENCES `mydb`.`Cinema_sessions` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
