#! /usr/bin/awk -f

BEGIN {
    t=0;
    for (i in ARGV) {

        if (i == 0) {
            continue;
        }

        if (ARGV[i] ~ /^[+-]?[0-9]+[.,]?[0-9]*$/) {
            t+=ARGV[i];
            continue;
        }

        print "Аргумент №" i " не является числом";
        exit 1;
    }
    print t;
}