FROM php:8.3-fpm

# Установка зависимостей и расширений
RUN apt-get update && apt-get install -y \
    libpq-dev \
    librabbitmq-dev \
    libssl-dev \
    build-essential \
    && docker-php-ext-install sockets \
    && pecl install amqp \
    && docker-php-ext-enable amqp