<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerLREH6kR\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerLREH6kR/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerLREH6kR.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerLREH6kR\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerLREH6kR\App_KernelDevDebugContainer([
    'container.build_hash' => 'LREH6kR',
    'container.build_id' => '439586b3',
    'container.build_time' => 1726761863,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerLREH6kR');
