server {
       listen         80;
       listen    [::]:80;
       server_name    montigomo.ru;
       return         301 https://$server_name$request_uri;
}

server {
    listen 443 ssl;
    listen [::]:443 ssl;

    root /app/public;

    server_name           montigomo.ru;
    ssl_certificate       /etc/letsencrypt/live/montigomo.ru/fullchain.pem;
    ssl_certificate_key   /etc/letsencrypt/live/montigomo.ru/privkey.pem;

    rewrite ^/index\.php/?(.*)$ /$1 permanent;

    try_files $uri @rewriteapp;

    location @rewriteapp {
        rewrite ^(.*)$ /index.php/$1 last;
    }

    location ~ /\. {
        deny all;
    }

    location ~ ^/index\.php(/|$) {
        fastcgi_split_path_info ^(.+\.php)(/.*)$;
        include fastcgi_params;
        fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
        fastcgi_param PATH_INFO $fastcgi_path_info;
        fastcgi_index index.php;
        send_timeout 1800;
        fastcgi_read_timeout 1800;
        fastcgi_pass php-telegram-bot-prod:9000;
    }

    error_log  /var/log/nginx/error.log;
    access_log /var/log/nginx/access.log;
}
