DROP TABLE IF EXISTS ticket;
DROP TABLE IF EXISTS session;
DROP TABLE IF EXISTS genre_movie;
DROP TABLE IF EXISTS movie;
DROP TABLE IF EXISTS genre;
DROP TABLE IF EXISTS country;
DROP TABLE IF EXISTS hall;
