<?php

declare(strict_types=1);

namespace AlexanderGladkov\CleanArchitecture\Infrastructure\Migration;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20240613103440 extends AbstractMigration
{
    public function getDescription(): string
    {
        return 'Create news table';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE public.news (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, created_at TIMESTAMP(0) WITH TIME ZONE NOT NULL, url TEXT NOT NULL, title VARCHAR(255) NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_A23C12FEF47645AE ON public.news (url)');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('DROP TABLE public.news');
    }

    /*
    public function up(Schema $schema): void
    {
        $table = $schema->createTable('news');
        $table->addColumn('id', Types::INTEGER, ['autoincrement' => true]);
        $table->addColumn('created_at', Types::DATETIMETZ_IMMUTABLE, [
            'notnull' => true,
            'default' => 'CURRENT_TIMESTAMP',
        ]);
        $table->addColumn('url', Types::TEXT, ['notnull' => true]);
        $table->addColumn('title', Types::STRING, ['length' => 255]);
        $table->setPrimaryKey(['id']);
        $table->addUniqueIndex(['url'], 'news__url__unique');
    }

    public function down(Schema $schema): void
    {
        $schema->dropTable('news');
    }
    */
}
