    [program:chat_update]
    command=php -dmemory_limit=1G /app/bin/console rabbitmq:consumer -m 100 chat_update -vv
    process_name=chat_update_%(process_num)02d
    numprocs=1
    directory=/tmp
    autostart=true
    autorestart=true
    startsecs=3
    startretries=10
    user=www-data
    redirect_stderr=false
    stdout_logfile=/app/var/log/supervisor.chat_update.out.log
    stdout_capture_maxbytes=1MB
    stderr_logfile=/app/var/log/supervisor.chat_update.error.log
    stderr_capture_maxbytes=1MB

    [program:send_message]
    command=php -dmemory_limit=1G /app/bin/console rabbitmq:consumer -m 100 send_message -vv
    process_name=send_message_%(process_num)02d
    numprocs=1
    directory=/tmp
    autostart=true
    autorestart=true
    startsecs=3
    startretries=10
    user=www-data
    redirect_stderr=false
    stdout_logfile=/app/var/log/supervisor.send_message.out.log
    stdout_capture_maxbytes=1MB
    stderr_logfile=/app/var/log/supervisor.send_message.error.log
    stderr_capture_maxbytes=1MB

    [program:edit_message]
    command=php -dmemory_limit=1G /app/bin/console rabbitmq:consumer -m 100 edit_message -vv
    process_name=edit_message_%(process_num)02d
    numprocs=1
    directory=/tmp
    autostart=true
    autorestart=true
    startsecs=3
    startretries=10
    user=www-data
    redirect_stderr=false
    stdout_logfile=/app/var/log/supervisor.edit_message.out.log
    stdout_capture_maxbytes=1MB
    stderr_logfile=/app/var/log/supervisor.edit_message.error.log
    stderr_capture_maxbytes=1MB
