upstream web-servers {
    least_conn;
    server web-server1;
    server web-server2;
}

server {
    listen 80;
    server_name mysite.local;
    location / {
        proxy_pass http://web-servers;
    }
}
