 upstream php-fpm {
        server php:9000;
    }

    # Блок server для обработки HTTP-запросов
    server {
        listen 80;  # Слушаем порт 80
        root /var/www/html/public_html;  # Корневая директория для файлов
        index index.html index.php;

     # Перенаправление всех запросов через index.php
      location / {
          try_files $uri $uri/ /index.php?$query_string;
     }

        # Обработка PHP-файлов
        location ~ \.php$ {
            include fastcgi_params;
            fastcgi_pass php-fpm;  # Используем upstream для балансировки
            fastcgi_index index.php;
            fastcgi_param SCRIPT_FILENAME $document_root/$fastcgi_script_name;

            # Проверка существования файла перед выполнением
            try_files $uri =404;
        }
    }