 upstream php-fpm {
        server php:9000;
    }

    # Блок server для обработки HTTP-запросов
    server {
        listen 80;  # Слушаем порт 80
        root /var/www/html/public_html;  # Корневая директория для файлов

        # Обработка статических файлов
        location / {
            index index.php index.html;
        }

        # Обработка PHP-файлов
        location ~ \.php$ {
            include fastcgi_params;
            fastcgi_pass php-fpm;  # Используем upstream для балансировки
            fastcgi_index index.php;
            fastcgi_param SCRIPT_FILENAME $document_root/$fastcgi_script_name;

            # Проверка существования файла перед выполнением
            try_files $uri =404;
        }
    }