nelmio_api_doc:
    documentation:
        info:
            title: Deferred Requests API
            description: API for managing statement requests with RabbitMQ
            version: 1.0.0
    areas: # to filter documented areas
        path_patterns:
            - ^/api(?!/doc$) # Accepts routes under /api except /api/doc
