nelmio_api_doc:
    documentation:
        info:
            title: Otus Api app
            description: App to create user requests and check requests statuses
            version: 1.0.0
    areas: # to filter documented areas
        path_patterns:
            - ^/api(?!/doc$) # Accepts routes under /api except /api/doc
